# Generated by Django 3.2.24 on 2024-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dateofbirth',
            field=models.DateField(null=True),
        ),
    ]
