# Generated by Django 3.2.24 on 2024-08-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('joined', models.DateField(null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
