# Generated by Django 3.2.24 on 2024-08-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20240823_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_authors', related_query_name='followed_authors', to='myapp.User'),
        ),
        migrations.AlterField(
            model_name='author',
            name='recommendedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_authors', related_query_name='recommended_authors', to='myapp.author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='myapp.publisher'),
        ),
    ]
