# Generated by Django 5.1 on 2024-08-26 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
